version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    logging:
      driver: 'none'
    ports:
      - "1025:1025"
      - "8025:8025"

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      # RabbitMQ instance
      - 5672:5672
      # Web interface
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/data
      - ~/.docker-conf/rabbitmq/log/:/var/lib/rabbitmq/log

  prometheus:
    container_name: "prometheus"
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    # configs:
    #   - source: prometheus_config
    #     target: /etc/prometheus/prometheus.yml
    volumes:
      # - ~/.docker-conf/prometheus/data/:/var/lib/prometheus/data
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    container_name: "grafana"
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ~/.docker-conf/grafana/data/:/var/lib/grafana/data
      
volumes:
  postgres:
  pgadmin:
  prometheus:
  grafana:
