{
 "title": "Microservice.Email",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Send email",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "send_email" }
   ]
  },
  {
   "title": "Send email errors",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "send_email_error" }
   ]
  },
  {
   "title": "Send templated emails",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "send_templated_email" }
   ]
  },
  {
   "title": "Send template email errors",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "send_templated_email_error" }
   ]
  }
 ]
}