# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      if: success()
    - name: Build
      run: dotnet build --no-restore
      if: success()
    - name: Unit tests
      run: dotnet test --no-build --verbosity normal
  
  # lint:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: read
  #     statuses: write
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: Lint Code Base
  #       uses: super-linter/super-linter@v5
  #       env:
  #         VALIDATE_ALL_CODEBASE: false
  #         VALIDATE_POWERSHELL: false
  #         VALIDATE_ARM: false
  #         DEFAULT_BRANCH: master
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
